server:
  port: 8002

logging:
  level:
    cn.zealon.book.** : debug

spring:
  profiles:
    include: data

  servlet:
    multipart:
      max-file-size: 2500MB
      max-request-size: 2500MB

#  jackson:
#    default-property-inclusion: non_null

  main:
    allow-bean-definition-overriding: true

# 系统属性文件配置
system:
  properties:
    upload-path: /Users/admin/local/
    attachment-dir: attachment/ #附件目录
    project-attachment-dir: project-attachment/ #项目文件附件目录
    head-access: /head/** #头像访问地址
    templates-access: /templates/** #模板访问地址
