spring:
  #---- MySQL配置  ----#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book-ms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 'pass123'
    initial-size: 5
    min-idle: 5
    max-active: 30
    max-wait: 60000

  #---- redis配置  ----#
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 30
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 10
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
      lettuce:
        pool:
          max-active: 30
          max-idle: 30
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
